[theme]
base = "light"

# Color primario para los widgets interactivos (botones, sliders, etc.)
primaryColor = "#1E88E5"

# Color de fondo para los widgets
# backgroundColor = ""
# secondaryBackgroundColor = ""